# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#

default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1       # Explicit IPv4 localhost for Windows
  port: 5432
  username: postgres     # Role you set in psql
  password: root         # Password you set with ALTER USER
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  database: my_application_development

test:
  <<: *default
  database: my_application_test

production:
  primary: &primary_production
    <<: *default
    database: my_application_production
    username: my_application
    password: <%= ENV["MY_APPLICATION_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: my_application_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_application_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_application_production_cable
    migrations_paths: db/cable_migrate